In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv("data/movies_converted.csv")

In [3]:
movies.head()

,id,title,overview,genre_ids,popularity,release_date,poster_path,vote_average,vote_count,genres
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[18, 80]",41.8985,1994-09-23,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,8.709,28228,"Drama,Crime"
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[18, 80]",34.4570,1972-03-14,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,8.686,21399,"Drama,Crime"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[18, 80]",14.8922,1974-12-20,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,8.570,12927,"Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"[18, 36, 10752]",43.5047,1993-12-15,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,8.564,16402,"Drama,History,War"
4,389,12 Angry Men,The defense and the prosecution have rested an...,[18],14.7159,1957-04-10,/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg,8.548,9102,Drama


In [4]:
movies = movies[["id", "title", "overview", "genres"]]

In [5]:
movies.head()

,id,title,overview,genres
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama,Crime"
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime"
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime"
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War"
4,389,12 Angry Men,The defense and the prosecution have rested an...,Drama


In [6]:
movies.loc[:, "tags"] = movies["overview"] + ' ' + movies["genres"] 

In [7]:
movies

,id,title,overview,genres,tags
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama,Crime",Imprisoned in the 1940s for the double murder ...
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama,Crime","Spanning the years 1945 to 1955, a chronicle o..."
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...,"Drama,Crime",In the continuing saga of the Corleone crime f...
3,424,Schindler's List,The true story of how businessman Oskar Schind...,"Drama,History,War",The true story of how businessman Oskar Schind...
4,389,12 Angry Men,The defense and the prosecution have rested an...,Drama,The defense and the prosecution have rested an...
...,...,...,...,...,...
9987,314,Catwoman,Liquidated after discovering a corporate consp...,"Action,Fantasy,Crime",Liquidated after discovering a corporate consp...
9988,765119,The Bubble,Sneaking out. Hooking up. Melting down. The ca...,Comedy,Sneaking out. Hooking up. Melting down. The ca...
9989,146203,The Last Exorcism Part II,"As Nell Sweetzer tries to build a new life, th...","Horror,Thriller","As Nell Sweetzer tries to build a new life, th..."
9990,87818,Movie 43,A series of interconnected short films are the...,Comedy,A series of interconnected short films are the...


In [8]:
new_data = movies.drop(columns=["overview", "genres"])

In [9]:
new_data

,id,title,tags
0,278,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...
1,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o..."
2,240,The Godfather Part II,In the continuing saga of the Corleone crime f...
3,424,Schindler's List,The true story of how businessman Oskar Schind...
4,389,12 Angry Men,The defense and the prosecution have rested an...
...,...,...,...
9987,314,Catwoman,Liquidated after discovering a corporate consp...
9988,765119,The Bubble,Sneaking out. Hooking up. Melting down. The ca...
9989,146203,The Last Exorcism Part II,"As Nell Sweetzer tries to build a new life, th..."
9990,87818,Movie 43,A series of interconnected short films are the...


In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [48]:
cv = CountVectorizer(stop_words="english")

In [49]:
cv

CountVectorizer(stop_words='english')

In [80]:
vector = cv.fit_transform(new_data["tags"].values.astype("U"))

In [81]:
vector = vector.toarray()

In [82]:
vector.shape

(9992, 27039)

In [83]:
vector

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(9992, 27039))

In [53]:
from sklearn.metrics.pairwise import cosine_similarity

In [54]:
similarity = cosine_similarity(vector)

In [55]:
similarity

array([[1.        , 0.11627907, 0.10166571, ..., 0.08151391, 0.        ,
        0.03569722],
       [0.11627907, 1.        , 0.48291214, ..., 0.04075696, 0.        ,
        0.01784861],
       [0.10166571, 0.48291214, 1.        , ..., 0.04454354, 0.04303315,
        0.03901372],
       ...,
       [0.08151391, 0.04075696, 0.04454354, ..., 1.        , 0.        ,
        0.06256112],
       [0.        , 0.        , 0.04303315, ..., 0.        , 1.        ,
        0.03021989],
       [0.03569722, 0.01784861, 0.03901372, ..., 0.06256112, 0.03021989,
        1.        ]], shape=(9992, 9992))

In [65]:
similarity.shape

(9992, 9992)

In [98]:
new_data[new_data["title"]=="The Bubble"]

,id,title,tags
9988,765119,The Bubble,Sneaking out. Hooking up. Melting down. The ca...


In [67]:
new_data[new_data["title"]=="The Godfather"].index[0]

np.int64(1)

In [90]:
distance = sorted(list(enumerate(similarity[238])), reverse=True, key=lambda vector:vector[1])

In [91]:
new_data.iloc[distance[1][0]]

id                                                  272878
title                                                  Max
tags     A dog that helped soldiers in Afghanistan retu...
Name: 2708, dtype: object

In [92]:
distance

[(238, np.float64(1.0)),
 (2708, np.float64(0.3952847075210474)),
 (1769, np.float64(0.38348249442368526)),
 (4553, np.float64(0.3296902366978935)),
 (277, np.float64(0.3265986323710904)),
 (929, np.float64(0.3265986323710904)),
 (1694, np.float64(0.30779350562554625)),
 (8072, np.float64(0.3069703067574603)),
 (1338, np.float64(0.30000000000000004)),
 (4226, np.float64(0.30000000000000004)),
 (2336, np.float64(0.298142396999972)),
 (3048, np.float64(0.298142396999972)),
 (4119, np.float64(0.298142396999972)),
 (9454, np.float64(0.298142396999972)),
 (4105, np.float64(0.28867513459481287)),
 (656, np.float64(0.2860387767736777)),
 (109, np.float64(0.2839809171235324)),
 (6545, np.float64(0.2760262237369417)),
 (706, np.float64(0.27386127875258315)),
 (2151, np.float64(0.27386127875258315)),
 (3390, np.float64(0.27386127875258315)),
 (6650, np.float64(0.27386127875258315)),
 (7764, np.float64(0.27386127875258315)),
 (1158, np.float64(0.2738612787525831)),
 (7366, np.float64(0.2696799449

In [133]:
new_data.iloc[distance[3][0]].title

'White Fang'

In [126]:
similarity[1]

array([0.10166571, 0.48291214, 1.        , ..., 0.04454354, 0.04303315,
       0.03901372], shape=(9992,))

In [94]:
new_data.iloc[distance[4][0]]

id                                                   28178
title                                  Hachi: A Dog's Tale
tags     A drama based on the true story of a college p...
Name: 277, dtype: object

In [112]:
def recommend(movies):
    index = new_data[new_data["title"]==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(new_data.iloc[i[0]].title)

In [113]:
recommend("The Scorpion King 3: Battle for Redemption")

The Scorpion King 3: Battle for Redemption
The Last Kingdom: Seven Kings Must Die
Doctor Strange
Mighty Morphin Power Rangers: The Movie
Descendants
